name: Deploy to Dev

on:
  workflow_dispatch: # click-to-deploy trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          echo “Building Docker Image...”
          docker build -t raman-micro:latest .

      - name: Deploy (Simulated)
        run: |
          echo “Simulated deployment...”

